name:                ReportGenerator
version:             0.1.0.0
github:              "Ofenhed/ReportGenerator"
license:             BSD3
author:              "Marcus Ofenhed"
maintainer:          "marcus.ofenhed@nixu.com"
copyright:           "2019 Marcus Ofenhed"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            A report generator for penetration testing reports.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Ofenhed/ReportGenerator#readme>

flags:
  llvm:
    description: Compile with much faster text search. Requires llvm >= 6.
    manual: True
    default: True
  Optimized:
    description: Optimize the output
    manual: True
    default: True

dependencies:
- base16-bytestring
- base >= 4.7 && < 5
- base64-bytestring
- bytestring
- containers
- cookie
- cryptonite
- Cvss3
- data-default
- data-default-class
- deepseq
- dlist
- file-embed
- filepath
- ginger
- http-types
- memory
- mtl
- network
- random
- safe
- scientific
- sqlite-simple
- template-haskell
- text
- time
- transformers
- vault
- vector
- wai
- wai-extra
- wai-session
- wai-websockets
- warp
- warp-tls
- websockets
- xml-conduit
- zlib

library:
  source-dirs:
    - src/
  when:
    - condition: flag(Optimized)
      ghc-options:
        - -O2
    - condition: flag(llvm)
      then:
        dependencies:
        - alfred-margaret
        source-dirs:
        - lib/textreplace-llvm/
      else:
        source-dirs:
        - lib/textreplace/

executables:
  ReportGenerator-exe:
    main:                Main.hs
    source-dirs:         app
    when:
      - condition: flag(Optimized)
        ghc-options:
        - -threaded
        - -O2
        - -rtsopts
        - -with-rtsopts=-N

    dependencies:
    - ReportGenerator

      # tests:
      #   ReportGenerator-test:
      #     main:                Spec.hs
      #     source-dirs:         test
      #     ghc-options:
      #     - -threaded
      #     - -rtsopts
      #     - -with-rtsopts=-N
      #     dependencies:
      #     - ReportGenerator
