name:                ReportGenerator
version:             0.1.0.0
github:              "Ofenhed/ReportGenerator"
license:             BSD3
author:              "Marcus Ofenhed"
maintainer:          "marcus.ofenhed@nixu.com"
copyright:           "2019 Marcus Ofenhed"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A report generator for penetration testing reports.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Ofenhed/ReportGenerator#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cryptonite
- data-default
- data-default-class
- dlist
- file-embed
- ginger
- http-types
- sqlite-simple
- text
- transformers
- vault
- vector
- wai
- wai-extra
- wai-session
- warp
  # - file-embed
  # - filepath
  # - random

library:
  source-dirs: src

executables:
  ReportGenerator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ReportGenerator

tests:
  ReportGenerator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ReportGenerator
